### PR TITLE
update README.md with install instructions

### PR DESCRIPTION
**Pull request by josenildoamorim**
solving the issue about readme.md and including install instructions

i also modified the download section, but leave the link blank :)

### CODE REVIEW

**Comment by Hrily** [comment]
It's a good work... :)
Try adding the instruction on how to build the app in Android Studio using the source, if you know it.
You may also want to add the installation procedure of  Android Studio (in brief, use links if necessary).

**Comment by josenildoamorim** [comment]
allright, ill do it

**Comment by josenildoamorim** [comment]
included instructions on how to setup android studio and work on code.

**Comment by Hrily** [comment]
Can you add the instructions for building project?
Also I updated the link, so I think you need to pull again to get the latest change.

**Comment by josenildoamorim** [comment]
i add a new commit with the download link a build instructions
not sure if these are the build instructions you want, but i did a link to a very complete post on android dev blog :)

**Comment by Hrily** [comment]
Okay, nice work... 👍 
I'll merge the request a little later and will let you know...

**Pull request merged**
